ALTER TABLE guides ADD COLUMN IF NOT EXISTS tipe VARCHAR(50) NOT NULL DEFAULT 'guide';
ALTER TABLE guides ADD COLUMN IF NOT EXISTS pdf_url TEXT;
ALTER TABLE guides ADD COLUMN IF NOT EXISTS pic_nama VARCHAR(255);
ALTER TABLE guides ADD COLUMN IF NOT EXISTS pic_email VARCHAR(255);
