ALTER TABLE guides DROP COLUMN IF EXISTS tipe;
ALTER TABLE guides DROP COLUMN IF EXISTS pdf_url;
ALTER TABLE guides DROP COLUMN IF EXISTS pic_nama;
ALTER TABLE guides DROP COLUMN IF EXISTS pic_email;
